language: python

python:
 - 2.7

env:
  global:
      - PIP_USE_MIRRORS=true
      - DOCKER_DATA="$HOME/docker_data"
      - BASE_USER_UID=2000
      - BASE_USER_GID=2000

install:
  - pip install -r requirements-test.txt
  - docker-compose -f docker-compose.deps.yml pull pip
  - docker-compose -f docker-compose.deps.yml run --rm pip
  - docker-compose -f docker-compose.yml pull

script:
  - docker-compose -f docker-compose.yml run --rm travis

notifications:
  email:
    on_success: change
    on_failure: always
