#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""Email field unique"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5a2a653aa3'
down_revision = '35b9c01dc584'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_registrations_email', table_name='api_registrations')
    op.create_index(op.f('ix_api_registrations_email'), 'api_registrations', ['email'], unique=True)
    op.drop_constraint(u'api_registrations_unique', 'api_registrations', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'api_registrations_unique', 'api_registrations', ['name', 'email'])
    op.drop_index(op.f('ix_api_registrations_email'), table_name='api_registrations')
    op.create_index('ix_api_registrations_email', 'api_registrations', ['email'], unique=False)
    # ### end Alembic commands ###
