#!/bin/bash
#
# This file is part of SCOAP3.
# Copyright (C) 2014-2018 CERN.
#
# SCOAP3 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SCOAP3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SCOAP3. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

set -e

scoap3 db drop --yes-i-know
scoap3 db create
scoap3 index destroy --force --yes-i-know
scoap3 index init

scoap3 fixdb init_default_location

scoap3 users create --active scoap3@scoap3.org
scoap3 roles create superadmin
scoap3 roles add scoap3@scoap3.org superadmin

if [[ "$1" != "--no-populate" ]]; then
  scoap3 loadrecords scoap3/data/scoap3demodata_short.json
fi
