#!/bin/bash
#
# This file is part of SCOAP3.
# Copyright (C) 2014-2018 CERN.
#
# SCOAP3 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SCOAP3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SCOAP3. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

set -e

if [ ! -d "${VIRTUAL_ENV}" ]; then
  >&2 echo "You must be in a virtual environment to use this script."
  exit 1
fi

if [ ! -x "$(command -v scoap3)" ]; then
  >&2 echo "You must have the SCOAP3 command to use this script."
  exit 1
fi

# FIXME: this is a hack should be moved to config.py or local cfg file
export APP_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://scoap3:dbpass123@localhost:5432/scoap3
export APP_CELERY_BROKER_URL=pyamqp://guest:guest@localhost:5672//
export APP_CELERY_RESULT_BACKEND=redis://localhost:6379/1
export CELERY_BROKER_URL=pyamqp://guest:guest@localhost:5672//
export CELERY_RESULT_BACKEND=redis://localhost:6379/1
export APP_CACHE_REDIS_URL=redis://localhost:6379/0
export APP_ACCOUNTS_SESSION_REDIS_URL=redis://localhost:6379/2
export APP_SEARCH_ELASTIC_HOSTS=localhost:9200
export APP_ES_BULK_TIMEOUT=240
export APP_CRAWLER_HOST_URL=http://localhost:6800
export APP_CRAWLER_API_PIPELINE_URL=http://flower:5555/api/task/async-apply
export APP_LAST_RUNS_PATH=.lastruns
export APP_OAIHARVESTER_WORKDIR=/virtualenv/oaiharvest_workdir
export APP_SERVER_NAME='localhost:5000'

scoap3 db drop --yes-i-know
scoap3 db create
scoap3 index destroy --force --yes-i-know
scoap3 index init

if [[ "$1" != "--no-populate" ]]; then
  scoap3 loadrecords scopa3/data/scoap3demodata.json
fi
