import requests_mock

from scoap3.cli_fixes import map_old_record
from tests.responses import read_hep_schema, read_titles_schema, read_response


class MockRecord:
    id = None

    def __init__(self, json):
        self.json = json


def run_mapper_with_mock(record, dry_run=True):
    with requests_mock.Mocker() as m:
        m.register_uri('GET', '/schemas/hep.json', content=read_hep_schema())
        m.register_uri('GET', '/schemas/elements/titles.json', content=read_titles_schema())
        m.register_uri('GET', 'http://export.arxiv.org/api/query?search_query=id:1308.1535',
                       content=read_response('arxiv', '1308.1535'))
        m.register_uri('GET', 'http://export.arxiv.org/api/query?search_query=id:1309.3748',
                       content=read_response('arxiv', '1309.3748'))
        m.register_uri('GET', 'http://export.arxiv.org/api/query?search_query=id:1501.04446',
                       content=read_response('arxiv', '1501.04446'))
        m.register_uri('GET', 'http://export.arxiv.org/api/query?search_query=id:1803.07709',
                       content=read_response('arxiv', '1803.07709'))
        return map_old_record(MockRecord(record), dry_run)


def test_map_old_record_ptep():
    data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_collections': [u'Progress of Theoretical and Experimental Physics',
                          u'scoap3'],
        u'_files': [{u'bucket': u'bc602784-c32d-456a-ba76-4a38181b3bd2',
                     u'checksum': u'md5:314a308cf2664a9dfeb3738369c22719',
                     u'filetype': u'xml',
                     u'key': u'10.1093/ptep/ptt095.xml',
                     u'size': 1091274,
                     u'version_id': u'7ca67df8-5e2d-4dde-a365-e3df3e414402'},
                    {u'bucket': u'bc602784-c32d-456a-ba76-4a38181b3bd2',
                     u'checksum': u'md5:fd2daa13aa14f22d05ab4dbd35697410',
                     u'filetype': u'pdf',
                     u'key': u'10.1093/ptep/ptt095.pdf',
                     u'size': 6319461,
                     u'version_id': u'921bc121-a390-42ec-8907-3faaee041e20'},
                    {u'bucket': u'bc602784-c32d-456a-ba76-4a38181b3bd2',
                     u'checksum': u'md5:d46f22db9ae4827fd90ff1a00fd28f6d',
                     u'filetype': u'pdf/a',
                     u'key': u'10.1093/ptep/ptt095_a.pdf',
                     u'size': 6551161,
                     u'version_id': u'33d47161-cfa1-4076-adb9-1425d8a6ec45'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:899',
                  u'sets': [u'PTEP'],
                  u'updated': u'2018-04-19T14:22:29Z'},
        u'abstracts': [{u'source': u'Oxford University Press/Physical Society of Japan',
                        u'value': u'Dense quantum [...] vortices, axial wallvortex composites, and Skyrmions.'}],
        u'acquisition_source': {u'date': u'2014-01-13T00:00:00',
                                u'method': u'scoap3',
                                u'source': u'Oxford University Press/Physical Society of Japan',
                                u'submission_number': u'c1e1d35643dc11e890c902163e01809a'},
        u'authors': [{u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Department of Physics, Yamagata University, Kojirakawa 1-4-12, '
                                                   u'Yamagata, Yamagata 990-8560, Japan'}],
                      u'full_name': u'Eto, Minoru',
                      u'given_names': u'Minoru',
                      u'raw_name': u'Eto, Minoru',
                      u'surname': u'Eto'},
                     {u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Theoretical Research Division, Nishina Center, RIKEN, Wako '
                                                   u'351-0198, Japan'},
                                        {u'country': u'Japan',
                                         u'value': u'Department of Physics, Sophia University, Tokyo 102-8554, Japan'},
                                        {u'country': u'Japan',
                                         u'value': u'Department of Physics, University of Tokyo, Hongo 7-3-1, '
                                                   u'Bunkyo-ku, Tokyo 113-0033, Japan'}],
                      u'full_name': u'Hirono, Yuji',
                      u'given_names': u'Yuji',
                      u'raw_name': u'Hirono, Yuji',
                      u'surname': u'Hirono'},
                     {u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Department of Physics, and Research and Education Center for '
                                                   u'Natural Sciences, Keio University, Hiyoshi 4-1-1, Yokohama, '
                                                   u'Kanagawa 223-8521, Japan'}],
                      u'full_name': u'Nitta, Muneto',
                      u'given_names': u'Muneto',
                      u'raw_name': u'Nitta, Muneto',
                      u'surname': u'Nitta'},
                     {u'affiliations': [{u'country': u'Japan',
                                         u'value': u'KEK Theory Center, Institute of Particle and Nuclear Studies, '
                                                   u'High Energy Accelerator Research Organization (KEK), 1-1 Oho, '
                                                   u'Tsukuba, Ibaraki 305-0801, Japan'}],
                      u'full_name': u'Yasui, Shigehiro',
                      u'given_names': u'Shigehiro',
                      u'raw_name': u'Yasui, Shigehiro',
                      u'surname': u'Yasui'}],
        u'control_number': u'899',
        u'copyright': [{u'holder': u'',
                        u'material': u'',
                        u'statement': u'The Author(s) 2014',
                        u'year': u'2014'}],
        u'dois': [{u'value': u'10.1093/ptep/ptt095'}],
        u'earliest_date': u'2014-01-01',
        u'files': [],
        u'imprints': [{u'date': u'2014-01-01',
                       u'publisher': u'Oxford University Press/Physical Society of Japan'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'http://creativecommons.org/licenses/by/3.0/'}],
        u'local_files': [{u'value': {u'filetype': u'xml',
                                     u'path': u'http://repo.scoap3.org/record/899/files/main.xml'}},
                         {u'value': {u'filetype': u'pdf',
                                     u'path': u'http://repo.scoap3.org/record/899/files/main.pdf'}},
                         {u'value': {u'filetype': u'pdfa',
                                     u'path': u'http://repo.scoap3.org/record/899/files/main.pdf?subformat=pdfa'}}],
        u'page_nr': [u'149'],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'1',
                               u'journal_title': u'Progress of Theoretical and Experimental Physics',
                               u'journal_volume': u'',
                               u'note': u'',
                               u'page_end': u'',
                               u'page_start': u'012D01',
                               u'pubinfo_freetext': u'',
                               u'year': 2014}],
        u'record_creation_date': u'2014-01-13',
        u'report_numbers': [{u'categories': [u'hep-ph',
                                             u'astro-ph.HE',
                                             u'cond-mat.supr-con',
                                             u'hep-th'],
                             u'primary_category': u'hep-ph',
                             u'source': u'arXiv',
                             u'value': u'arXiv:1308.1535'}],
        u'titles': [{u'source': u'Oxford University Press/Physical Society of Japan',
                     u'subtitle': u'',
                     u'title': u'Vortices and other topological solitons in dense quark matter'}]
    }

    expected_data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_files': [{u'bucket': u'bc602784-c32d-456a-ba76-4a38181b3bd2',
                     u'checksum': u'md5:314a308cf2664a9dfeb3738369c22719',
                     u'filetype': u'xml',
                     u'key': u'10.1093/ptep/ptt095.xml',
                     u'size': 1091274,
                     u'version_id': u'7ca67df8-5e2d-4dde-a365-e3df3e414402'},
                    {u'bucket': u'bc602784-c32d-456a-ba76-4a38181b3bd2',
                     u'checksum': u'md5:fd2daa13aa14f22d05ab4dbd35697410',
                     u'filetype': u'pdf',
                     u'key': u'10.1093/ptep/ptt095.pdf',
                     u'size': 6319461,
                     u'version_id': u'921bc121-a390-42ec-8907-3faaee041e20'},
                    {u'bucket': u'bc602784-c32d-456a-ba76-4a38181b3bd2',
                     u'checksum': u'md5:d46f22db9ae4827fd90ff1a00fd28f6d',
                     u'filetype': u'pdf/a',
                     u'key': u'10.1093/ptep/ptt095_a.pdf',
                     u'size': 6551161,
                     u'version_id': u'33d47161-cfa1-4076-adb9-1425d8a6ec45'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:899',
                  u'sets': [u'PTEP'],
                  u'updated': u'2018-04-19T14:22:29Z'},
        u'abstracts': [{u'source': u'Oxford University Press/Physical Society of Japan',
                        u'value': u'Dense quantum [...] vortices, axial wallvortex composites, and Skyrmions.'}],
        u'acquisition_source': {u'date': u'2014-01-13T00:00:00',
                                u'method': u'scoap3',
                                u'source': u'Oxford University Press/Physical Society of Japan',
                                u'submission_number': u'c1e1d35643dc11e890c902163e01809a'},
        u'authors': [{u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Department of Physics, Yamagata University, Kojirakawa 1-4-12, '
                                                   u'Yamagata, Yamagata 990-8560, Japan'}],
                      u'full_name': u'Eto, Minoru',
                      u'given_names': u'Minoru',
                      u'raw_name': u'Eto, Minoru',
                      u'surname': u'Eto'},
                     {u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Theoretical Research Division, Nishina Center, RIKEN, Wako '
                                                   u'351-0198, Japan'},
                                        {u'country': u'Japan',
                                         u'value': u'Department of Physics, Sophia University, Tokyo 102-8554, Japan'},
                                        {u'country': u'Japan',
                                         u'value': u'Department of Physics, University of Tokyo, Hongo 7-3-1, '
                                                   u'Bunkyo-ku, Tokyo 113-0033, Japan'}],
                      u'full_name': u'Hirono, Yuji',
                      u'given_names': u'Yuji',
                      u'raw_name': u'Hirono, Yuji',
                      u'surname': u'Hirono'},
                     {u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Department of Physics, and Research and Education Center for '
                                                   u'Natural Sciences, Keio University, Hiyoshi 4-1-1, Yokohama, '
                                                   u'Kanagawa 223-8521, Japan'}],
                      u'full_name': u'Nitta, Muneto',
                      u'given_names': u'Muneto',
                      u'raw_name': u'Nitta, Muneto',
                      u'surname': u'Nitta'},
                     {u'affiliations': [{u'country': u'Japan',
                                         u'value': u'KEK Theory Center, Institute of Particle and Nuclear Studies, '
                                                   u'High Energy Accelerator Research Organization (KEK), 1-1 Oho, '
                                                   u'Tsukuba, Ibaraki 305-0801, Japan'}],
                      u'full_name': u'Yasui, Shigehiro',
                      u'given_names': u'Shigehiro',
                      u'raw_name': u'Yasui, Shigehiro',
                      u'surname': u'Yasui'}],
        u'control_number': u'899',
        u'copyright': [{u'holder': u'',
                        u'material': u'',
                        u'statement': u'The Author(s) 2014',
                        u'year': u'2014'}],
        u'dois': [{u'value': u'10.1093/ptep/ptt095'}],
        u'imprints': [{u'date': u'2014-01-01',
                       u'publisher': u'Oxford University Press/Physical Society of Japan'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'http://creativecommons.org/licenses/by/3.0/'}],
        u'page_nr': [149],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'1',
                               u'journal_title': u'Progress of Theoretical and Experimental Physics',
                               u'journal_volume': u'',
                               u'note': u'',
                               u'page_end': u'',
                               u'page_start': u'012D01',
                               u'pubinfo_freetext': u'',
                               u'year': 2014}],
        u'record_creation_date': u'2014-01-13T00:00:00',
        u'arxiv_eprints': [{u'categories': [u'hep-ph', u'astro-ph.HE', u'cond-mat.supr-con', u'hep-th'],
                            u'value': u'1308.1535'}],
        u'titles': [{u'source': u'Oxford University Press/Physical Society of Japan',
                     u'subtitle': u'',
                     u'title': u'Vortices and other topological solitons in dense quark matter'}]}

    assert run_mapper_with_mock(data).json == expected_data


def test_map_old_record_elsevier():
    data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_collections': [u'Physics Letters B', u'scoap3'],
        u'_files': [{u'bucket': u'edb0e9fd-79b5-48c3-852b-0953ece4fcb0',
                     u'checksum': u'md5:93a430e97abf71eade39bfcbde8453a8',
                     u'filetype': u'xml',
                     u'key': u'10.1016/j.physletb.2013.11.039.xml',
                     u'size': 184214,
                     u'version_id': u'1a139dea-dcf6-494d-a03c-d397e918140a'},
                    {u'bucket': u'edb0e9fd-79b5-48c3-852b-0953ece4fcb0',
                     u'checksum': u'md5:bd8341f03a23c50123bc09b8ae5c72b0',
                     u'filetype': u'pdf',
                     u'key': u'10.1016/j.physletb.2013.11.039.pdf',
                     u'size': 306193,
                     u'version_id': u'e2f54f92-207f-410e-bd6e-dd4c3cd9703a'},
                    {u'bucket': u'edb0e9fd-79b5-48c3-852b-0953ece4fcb0',
                     u'checksum': u'md5:2517c8a46c60c5c402bb33f2a2bb349b',
                     u'filetype': u'pdf/a',
                     u'key': u'10.1016/j.physletb.2013.11.039_a.pdf',
                     u'size': 573522,
                     u'version_id': u'51c4dd3b-e229-4755-bf24-caaf0fa92c9c'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:757',
                  u'sets': [u'PLB'],
                  u'updated': u'2018-04-18T13:08:49Z'},
        u'abstracts': [{u'source': u'Elsevier',
                        u'value': u'Light sterile neutrinos of [...] or solar neutrino experiments.'}],
        u'acquisition_source': {u'date': u'2014-01-08T00:00:00',
                                u'method': u'scoap3',
                                u'source': u'Elsevier',
                                u'submission_number': u'37226564430511e898b102163e01809a'},
        u'authors': [{u'affiliations': [{u'country': u'Taiwan',
                                         u'value': u'CTS, CASTS, Department of Physics, National Taiwan University, '
                                                   u'Taipei, Taiwan'},
                                        {u'country': u'China',
                                         u'value': u'Shanghai Key Laboratory of Particle Physics and Cosmology, '
                                                   u'Shanghai, China'},
                                        {u'country': u'China',
                                         u'value': u'INPAC, Department of Physics, Shanghai Jiao Tong University, '
                                                   u'Shanghai, China'},
                                        {u'country': u'Taiwan',
                                         u'value': u'Physics Division, National Center for Theoretical Sciences, '
                                                   u'Department of Physics, National Tsing Hua University, Hsinchu, '
                                                   u'Taiwan'}],
                      u'full_name': u'He, Xiao-Gang',
                      u'given_names': u'Xiao-Gang',
                      u'raw_name': u'He, Xiao-Gang',
                      u'surname': u'He'},
                     {u'affiliations': [{u'country': u'China',
                                         u'value': u'Institute of Modern Physics, School of Science, East China '
                                                   u'University of Science and Technology, Shanghai, China'}],
                      u'full_name': u'Liao, Wei',
                      u'given_names': u'Wei',
                      u'raw_name': u'Liao, Wei',
                      u'surname': u'Liao'}],
        u'control_number': u'757',
        u'copyright': [{u'holder': u'',
                        u'material': u'',
                        u'statement': u'The Authors',
                        u'year': u''}],
        u'dois': [{u'value': u'10.1016/j.physletb.2013.11.039'}],
        u'earliest_date': u'2014-01-20',
        u'files': [],
        u'imprints': [{u'date': u'2014-01-20', u'publisher': u'Elsevier'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'http://creativecommons.org/licenses/by/3.0/'}],
        u'local_files': [{u'value': {u'filetype': u'xml',
                                     u'path': u'http://repo.scoap3.org/record/757/files/main.xml'}},
                         {u'value': {u'filetype': u'pdf',
                                     u'path': u'http://repo.scoap3.org/record/757/files/main.pdf'}},
                         {u'value': {u'filetype': u'pdfa',
                                     u'path': u'http://repo.scoap3.org/record/757/files/main.pdf?subformat=pdfa'}}],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'',
                               u'journal_title': u'Physics Letters B',
                               u'journal_volume': u'',
                               u'note': u'',
                               u'page_end': u'72',
                               u'page_start': u'68',
                               u'pubinfo_freetext': u'',
                               u'year': 2014}],
        u'record_creation_date': u'2014-01-08',
        u'titles': [{u'source': u'Elsevier',
                     u'subtitle': u'',
                     u'title': u'A light sterile neutrino from Friedberg\xe2\x80\x93Lee symmetry'}]
    }

    expected_data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_files': [{u'bucket': u'edb0e9fd-79b5-48c3-852b-0953ece4fcb0',
                     u'checksum': u'md5:93a430e97abf71eade39bfcbde8453a8',
                     u'filetype': u'xml',
                     u'key': u'10.1016/j.physletb.2013.11.039.xml',
                     u'size': 184214,
                     u'version_id': u'1a139dea-dcf6-494d-a03c-d397e918140a'},
                    {u'bucket': u'edb0e9fd-79b5-48c3-852b-0953ece4fcb0',
                     u'checksum': u'md5:bd8341f03a23c50123bc09b8ae5c72b0',
                     u'filetype': u'pdf',
                     u'key': u'10.1016/j.physletb.2013.11.039.pdf',
                     u'size': 306193,
                     u'version_id': u'e2f54f92-207f-410e-bd6e-dd4c3cd9703a'},
                    {u'bucket': u'edb0e9fd-79b5-48c3-852b-0953ece4fcb0',
                     u'checksum': u'md5:2517c8a46c60c5c402bb33f2a2bb349b',
                     u'filetype': u'pdf/a',
                     u'key': u'10.1016/j.physletb.2013.11.039_a.pdf',
                     u'size': 573522,
                     u'version_id': u'51c4dd3b-e229-4755-bf24-caaf0fa92c9c'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:757',
                  u'sets': [u'PLB'],
                  u'updated': u'2018-04-18T13:08:49Z'},
        u'abstracts': [{u'source': u'Elsevier',
                        u'value': u'Light sterile neutrinos of [...] or solar neutrino experiments.'}],
        u'acquisition_source': {u'date': u'2014-01-08T00:00:00',
                                u'method': u'scoap3',
                                u'source': u'Elsevier',
                                u'submission_number': u'37226564430511e898b102163e01809a'},
        u'authors': [{u'affiliations': [{u'country': u'Taiwan',
                                         u'value': u'CTS, CASTS, Department of Physics, National Taiwan University, '
                                                   u'Taipei, Taiwan'},
                                        {u'country': u'China',
                                         u'value': u'Shanghai Key Laboratory of Particle Physics and Cosmology, '
                                                   u'Shanghai, China'},
                                        {u'country': u'China',
                                         u'value': u'INPAC, Department of Physics, Shanghai Jiao Tong University, '
                                                   u'Shanghai, China'},
                                        {u'country': u'Taiwan',
                                         u'value': u'Physics Division, National Center for Theoretical Sciences, '
                                                   u'Department of Physics, National Tsing Hua University, Hsinchu, '
                                                   u'Taiwan'}],
                      u'full_name': u'He, Xiao-Gang',
                      u'given_names': u'Xiao-Gang',
                      u'raw_name': u'He, Xiao-Gang',
                      u'surname': u'He'},
                     {u'affiliations': [{u'country': u'China',
                                         u'value': u'Institute of Modern Physics, School of Science, East China Unive'
                                                   u'rsity of Science and Technology, Shanghai, China'}],
                      u'full_name': u'Liao, Wei',
                      u'given_names': u'Wei',
                      u'raw_name': u'Liao, Wei',
                      u'surname': u'Liao'}],
        u'control_number': u'757',
        u'copyright': [{u'holder': u'',
                        u'material': u'',
                        u'statement': u'The Authors',
                        u'year': u''}],
        u'dois': [{u'value': u'10.1016/j.physletb.2013.11.039'}],
        u'imprints': [{u'date': u'2014-01-20', u'publisher': u'Elsevier'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'http://creativecommons.org/licenses/by/3.0/'}],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'',
                               u'journal_title': u'Physics Letters B',
                               u'journal_volume': u'',
                               u'note': u'',
                               u'page_end': u'72',
                               u'page_start': u'68',
                               u'pubinfo_freetext': u'',
                               u'year': 2014}],
        u'record_creation_date': u'2014-01-08T00:00:00',
        u'titles': [{u'source': u'Elsevier',
                     u'subtitle': u'',
                     u'title': u'A light sterile neutrino from Friedberg\xe2\x80\x93Lee symmetry'}]
    }

    assert run_mapper_with_mock(data).json == expected_data


def test_map_old_record_SISSA():
    data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_collections': [u'Journal of Cosmology and Astroparticle Physics',
                          u'scoap3'],
        u'_files': [{u'bucket': u'930dfb98-9b1f-4cc0-8446-b90ad0fd60b6',
                     u'checksum': u'md5:44ce3424291b588eb8c59f9a4d527fd7',
                     u'filetype': u'pdf',
                     u'key': u'10.1088/1475-7516/2014/01/008.pdf',
                     u'size': 705969,
                     u'version_id': u'936711b9-844c-446e-bc39-856b171b8025'},
                    {u'bucket': u'930dfb98-9b1f-4cc0-8446-b90ad0fd60b6',
                     u'checksum': u'md5:c49a927ba18aecb0214015b59191fc8e',
                     u'filetype': u'xml',
                     u'key': u'10.1088/1475-7516/2014/01/008.xml',
                     u'size': 107304,
                     u'version_id': u'9e2f7466-bd54-407d-a51f-63c09992e7e5'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:787',
                  u'sets': [],
                  u'updated': u'2018-04-12T19:25:37Z'},
        u'abstracts': [{u'source': u'Institute of Physics Publishing/SISSA',
                        u'value': u'We reconstruct F(R) gravity [...] expansion rates are different each other.'}],
        u'acquisition_source': {u'date': u'2014-01-08T00:00:00',
                                u'method': u'scoap3',
                                u'source': u'Institute of Physics Publishing/SISSA',
                                u'submission_number': u'1f12c56a3e8511e881c402163e01809a'},
        u'authors': [{u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Kobayashi-Maskawa Institute for the Origin of Particles and the '
                                                   u'Universe, Nagoya University, Nagoya 464-8602, Japan'}],
                      u'full_name': u'Bamba, Kazuharu',
                      u'given_names': u'Kazuharu',
                      u'raw_name': u'Bamba, Kazuharu',
                      u'surname': u'Bamba'},
                     {u'affiliations': [{u'country': u'Russia',
                                         u'value': u'Tomsk State Pedagogical University, Kievskaya Avenue, 60, 634061, '
                                                   u'Tomsk, Russia'}],
                      u'full_name': u'Makarenko, Andrey N.',
                      u'given_names': u'Andrey N.',
                      u'raw_name': u'Makarenko, Andrey N.',
                      u'surname': u'Makarenko'},
                     {u'affiliations': [{u'country': u'Russia',
                                         u'value': u'Tomsk Polytechnic University, Lenin Avenue, 30, 634050,'
                                                   u' Tomsk, Russia'}],
                      u'full_name': u'Myagky, Alexandr N.',
                      u'given_names': u'Alexandr N.',
                      u'raw_name': u'Myagky, Alexandr N.',
                      u'surname': u'Myagky'},
                     {u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Department of Physics, Nagoya University, Nagoya 464-8602, Japan'},
                                        {u'country': u'Japan',
                                         u'value': u'Kobayashi-Maskawa Institute for the Origin of Particles and the '
                                                   u'Universe, Nagoya University, Nagoya 464-8602, Japan'}],
                      u'full_name': u"Nojiri, Shin'ichi",
                      u'given_names': u"Shin'ichi",
                      u'raw_name': u"Nojiri, Shin'ichi",
                      u'surname': u'Nojiri'},
                     {u'affiliations': [{u'country': u'Russia',
                                         u'value': u'Tomsk State Pedagogical University, Kievskaya Avenue, 60, 634061,'
                                                   u' Tomsk, Russia'},
                                        {u'country': u'Spain',
                                         u'value': u'Instituci\xc3\xb2 Catalana de Recerca i Estudis Avan\xc3\xa7ats '
                                                   u'(ICREA), Barcelona, Spain'},
                                        {u'country': u'Spain',
                                         u'value': u"Institut de Ciencies de l'Espai (CSIC-IEEC), Campus UAB, Facultat "
                                                   u"de Ciencies, Torre C5-Par-2a pl, E-08193 Bellaterra (Barcelona),"
                                                   u" Spain"}],
                      u'full_name': u'Odintsov, Sergei D.',
                      u'given_names': u'Sergei D.',
                      u'raw_name': u'Odintsov, Sergei D.',
                      u'surname': u'Odintsov'}],
        u'control_number': u'787',
        u'copyright': [{u'holder': u'',
                        u'material': u'',
                        u'statement': u'',
                        u'year': u''}],
        u'dois': [{u'value': u'10.1088/1475-7516/2014/01/008'}],
        u'earliest_date': u'2014-01-01',
        u'files': [],
        u'imprints': [{u'date': u'2014-01-01',
                       u'publisher': u'Institute of Physics Publishing/SISSA'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'http://creativecommons.org/licenses/by/3.0/'}],
        u'local_files': [{u'value': {u'filetype': u'pdf',
                                     u'path': u'http://repo.scoap3.org/record/787/files/fulltext.pdf'}},
                         {u'value': {u'filetype': u'xml',
                                     u'path': u'http://repo.scoap3.org/record/787/files/fulltext.xml'}}],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'01',
                               u'journal_title': u'Journal of Cosmology and Astroparticle Physics',
                               u'journal_volume': u'',
                               u'note': u'',
                               u'page_end': u'',
                               u'page_start': u'008',
                               u'pubinfo_freetext': u'',
                               u'year': 2014}],
        u'record_creation_date': u'2014-01-08',
        u'report_numbers': [{u'categories': [u'hep-th', u'astro-ph.CO', u'gr-qc'],
                             u'primary_category': u'hep-th',
                             u'source': u'arXiv',
                             u'value': u'arXiv:1309.3748'}],
        u'titles': [{u'source': u'Institute of Physics Publishing/SISSA',
                     u'subtitle': u'',
                     u'title': u'Bounce cosmology from F(R) gravity and F(R) bigravity'}]
    }

    expected_data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_files': [{u'bucket': u'930dfb98-9b1f-4cc0-8446-b90ad0fd60b6',
                     u'checksum': u'md5:44ce3424291b588eb8c59f9a4d527fd7',
                     u'filetype': u'pdf',
                     u'key': u'10.1088/1475-7516/2014/01/008.pdf',
                     u'size': 705969,
                     u'version_id': u'936711b9-844c-446e-bc39-856b171b8025'},
                    {u'bucket': u'930dfb98-9b1f-4cc0-8446-b90ad0fd60b6',
                     u'checksum': u'md5:c49a927ba18aecb0214015b59191fc8e',
                     u'filetype': u'xml',
                     u'key': u'10.1088/1475-7516/2014/01/008.xml',
                     u'size': 107304,
                     u'version_id': u'9e2f7466-bd54-407d-a51f-63c09992e7e5'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:787',
                  u'sets': [],
                  u'updated': u'2018-04-12T19:25:37Z'},
        u'abstracts': [{u'source': u'Institute of Physics Publishing/SISSA',
                        u'value': u'We reconstruct F(R) gravity [...] expansion rates are different each other.'}],
        u'acquisition_source': {u'date': u'2014-01-08T00:00:00',
                                u'method': u'scoap3',
                                u'source': u'Institute of Physics Publishing/SISSA',
                                u'submission_number': u'1f12c56a3e8511e881c402163e01809a'},
        u'authors': [{u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Kobayashi-Maskawa Institute for the Origin of Particles and the'
                                                   u' Universe, Nagoya University, Nagoya 464-8602, Japan'}],
                      u'full_name': u'Bamba, Kazuharu',
                      u'given_names': u'Kazuharu',
                      u'raw_name': u'Bamba, Kazuharu',
                      u'surname': u'Bamba'},
                     {u'affiliations': [{u'country': u'Russia',
                                         u'value': u'Tomsk State Pedagogical University, Kievskaya Avenue, 60, 634061,'
                                                   u' Tomsk, Russia'}],
                      u'full_name': u'Makarenko, Andrey N.',
                      u'given_names': u'Andrey N.',
                      u'raw_name': u'Makarenko, Andrey N.',
                      u'surname': u'Makarenko'},
                     {u'affiliations': [{u'country': u'Russia',
                                         u'value': u'Tomsk Polytechnic University, Lenin Avenue, 30, 634050, Tomsk,'
                                                   u' Russia'}],
                      u'full_name': u'Myagky, Alexandr N.',
                      u'given_names': u'Alexandr N.',
                      u'raw_name': u'Myagky, Alexandr N.',
                      u'surname': u'Myagky'},
                     {u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Department of Physics, Nagoya University, Nagoya 464-8602, Japan'},
                                        {u'country': u'Japan',
                                         u'value': u'Kobayashi-Maskawa Institute for the Origin of Particles and the'
                                                   u' Universe, Nagoya University, Nagoya 464-8602, Japan'}],
                      u'full_name': u"Nojiri, Shin'ichi",
                      u'given_names': u"Shin'ichi",
                      u'raw_name': u"Nojiri, Shin'ichi",
                      u'surname': u'Nojiri'},
                     {u'affiliations': [{u'country': u'Russia',
                                         u'value': u'Tomsk State Pedagogical University, Kievskaya Avenue, 60, 634061,'
                                                   u' Tomsk, Russia'},
                                        {u'country': u'Spain',
                                         u'value': u'Instituci\xc3\xb2 Catalana de Recerca i Estudis Avan\xc3\xa7ats '
                                                   u'(ICREA), Barcelona, Spain'},
                                        {u'country': u'Spain',
                                         u'value': u"Institut de Ciencies de l'Espai (CSIC-IEEC), Campus UAB, Facultat"
                                                   u" de Ciencies, Torre C5-Par-2a pl, E-08193 Bellaterra (Barcelona)"
                                                   u", Spain"}],
                      u'full_name': u'Odintsov, Sergei D.',
                      u'given_names': u'Sergei D.',
                      u'raw_name': u'Odintsov, Sergei D.',
                      u'surname': u'Odintsov'}],
        u'control_number': u'787',
        u'copyright': [{u'holder': u'',
                        u'material': u'',
                        u'statement': u'',
                        u'year': u''}],
        u'dois': [{u'value': u'10.1088/1475-7516/2014/01/008'}],
        u'imprints': [{u'date': u'2014-01-01',
                       u'publisher': u'Institute of Physics Publishing/SISSA'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'http://creativecommons.org/licenses/by/3.0/'}],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'01',
                               u'journal_title': u'Journal of Cosmology and Astroparticle Physics',
                               u'journal_volume': u'',
                               u'note': u'',
                               u'page_end': u'',
                               u'page_start': u'008',
                               u'pubinfo_freetext': u'',
                               u'year': 2014}],
        u'record_creation_date': u'2014-01-08T00:00:00',
        u'arxiv_eprints': [{u'categories': [u'hep-th', u'astro-ph.CO', u'gr-qc'],
                            u'value': u'1309.3748'}],
        u'titles': [{u'source': u'Institute of Physics Publishing/SISSA',
                     u'subtitle': u'',
                     u'title': u'Bounce cosmology from F(R) gravity and F(R) bigravity'}]
    }

    assert run_mapper_with_mock(data).json == expected_data


def test_map_old_record_jagiellonian():
    data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_collections': [u'Acta Physica Polonica B', u'scoap3'],
        u'_files': [{u'bucket': u'20119708-2116-4a93-94b6-f54a4062d855',
                     u'checksum': u'md5:4d3bcfa6c04e1c5e69b36bbbe4f8bd06',
                     u'filetype': u'pdf',
                     u'key': u'10.5506/APhysPolB.46.45.pdf',
                     u'size': 957545,
                     u'version_id': u'af975e8f-ef22-446a-a165-cb0831dc782a'},
                    {u'bucket': u'20119708-2116-4a93-94b6-f54a4062d855',
                     u'checksum': u'md5:9abdfcc10ba94451b42ec68e4ca6ace1',
                     u'filetype': u'pdf/a',
                     u'key': u'10.5506/APhysPolB.46.45_a.pdf',
                     u'size': 242804,
                     u'version_id': u'1b016a78-f349-4d6f-8d71-6dd12ad54039'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:9141',
                  u'sets': [u'APPB'],
                  u'updated': u'2018-04-12T11:48:20Z'},
        u'abstracts': [{u'source': u'Jagiellonian University',
                        u'value': u'The measurement of the [...] will be presented in the following.'}],
        u'acquisition_source': {u'date': u'2015-02-11T00:00:00',
                                u'method': u'scoap3',
                                u'source': u'Jagiellonian University',
                                u'submission_number': u'37c2dc643e4711e881c402163e01809a'},
        u'authors': [{u'affiliations': [{u'country': u'Italy',
                                         u'value': u"Universita` degli Studi di Messina Dipartimento di Fisica e "
                                                   u"Scienze della Terra, Viale F. Stagno D'Alcontres 31, 98166 "
                                                   u"Messina, Italy"}],
                      u'full_name': u'De Leo, Veronica',
                      u'given_names': u'Veronica',
                      u'raw_name': u'De Leo, Veronica',
                      u'surname': u'De Leo'}],
        u'control_number': u'9141',
        u'copyright': [{u'holder': u'',
                        u'material': u'',
                        u'statement': u'The Author',
                        u'year': u''}],
        u'dois': [{u'value': u'10.5506/APhysPolB.46.45'}],
        u'earliest_date': u'2015-01-01',
        u'files': [],
        u'imprints': [{u'date': u'2015-01-01',
                       u'publisher': u'Jagiellonian University'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'http://creativecommons.org/licenses/by/3.0/'}],
        u'local_files': [{u'value': {u'filetype': u'pdf',
                                     u'path': u'http://repo.scoap3.org/record/9141/files/fulltext.pdf'}},
                         {u'value': {u'filetype': u'pdfa',
                                     u'path': u'http://repo.scoap3.org/record/9141/files/fulltext.pdf'
                                              u'?subformat=pdfa'}}],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'1',
                               u'journal_title': u'Acta Physica Polonica B',
                               u'journal_volume': u'',
                               u'note': u'',
                               u'page_end': u'51',
                               u'page_start': u'45',
                               u'pubinfo_freetext': u'',
                               u'year': 2015}],
        u'record_creation_date': u'2015-02-11',
        u'report_numbers': [{u'categories': [u'hep-ex'],
                             u'primary_category': u'hep-ex',
                             u'source': u'arXiv',
                             u'value': u'arXiv:1501.04446'}],
        u'titles': [{u'source': u'Jagiellonian University',
                     u'subtitle': u'',
                     u'title': u'Measurement of Hadronic Cross Section at KLOE/KLOE-2'}]
    }

    expected_data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_files': [{u'bucket': u'20119708-2116-4a93-94b6-f54a4062d855',
                     u'checksum': u'md5:4d3bcfa6c04e1c5e69b36bbbe4f8bd06',
                     u'filetype': u'pdf',
                     u'key': u'10.5506/APhysPolB.46.45.pdf',
                     u'size': 957545,
                     u'version_id': u'af975e8f-ef22-446a-a165-cb0831dc782a'},
                    {u'bucket': u'20119708-2116-4a93-94b6-f54a4062d855',
                     u'checksum': u'md5:9abdfcc10ba94451b42ec68e4ca6ace1',
                     u'filetype': u'pdf/a',
                     u'key': u'10.5506/APhysPolB.46.45_a.pdf',
                     u'size': 242804,
                     u'version_id': u'1b016a78-f349-4d6f-8d71-6dd12ad54039'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:9141',
                  u'sets': [u'APPB'],
                  u'updated': u'2018-04-12T11:48:20Z'},
        u'abstracts': [{u'source': u'Jagiellonian University',
                        u'value': u'The measurement of the [...] will be presented in the following.'}],
        u'acquisition_source': {u'date': u'2015-02-11T00:00:00',
                                u'method': u'scoap3',
                                u'source': u'Jagiellonian University',
                                u'submission_number': u'37c2dc643e4711e881c402163e01809a'},
        u'authors': [{u'affiliations': [{u'country': u'Italy',
                                         u'value': u"Universita` degli Studi di Messina Dipartimento di Fisica e "
                                                   u"Scienze della Terra, Viale F. Stagno D'Alcontres 31, 98166 "
                                                   u"Messina, Italy"}],
                      u'full_name': u'De Leo, Veronica',
                      u'given_names': u'Veronica',
                      u'raw_name': u'De Leo, Veronica',
                      u'surname': u'De Leo'}],
        u'control_number': u'9141',
        u'copyright': [{u'holder': u'',
                        u'material': u'',
                        u'statement': u'The Author',
                        u'year': u''}],
        u'dois': [{u'value': u'10.5506/APhysPolB.46.45'}],
        u'imprints': [{u'date': u'2015-01-01',
                       u'publisher': u'Jagiellonian University'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'http://creativecommons.org/licenses/by/3.0/'}],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'1',
                               u'journal_title': u'Acta Physica Polonica B',
                               u'journal_volume': u'',
                               u'note': u'',
                               u'page_end': u'51',
                               u'page_start': u'45',
                               u'pubinfo_freetext': u'',
                               u'year': 2015}],
        u'record_creation_date': u'2015-02-11T00:00:00',
        u'arxiv_eprints': [{u'categories': [u'hep-ex'],
                            u'value': u'1501.04446'}],
        u'titles': [{u'source': u'Jagiellonian University',
                     u'subtitle': u'',
                     u'title': u'Measurement of Hadronic Cross Section at KLOE/KLOE-2'}]
    }

    assert run_mapper_with_mock(data).json == expected_data


def test_map_old_record_broken_report_numbers():
    """Both report_numbers and arxiv_eprints fields are present."""

    data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_collections': [u'Progress of Theoretical and Experimental Physics',
                          u'scoap3'],
        u'_files': [{u'bucket': u'bc602784-c32d-456a-ba76-4a38181b3bd2',
                     u'checksum': u'md5:314a308cf2664a9dfeb3738369c22719',
                     u'filetype': u'xml',
                     u'key': u'10.1093/ptep/ptt095.xml',
                     u'size': 1091274,
                     u'version_id': u'7ca67df8-5e2d-4dde-a365-e3df3e414402'},
                    {u'bucket': u'bc602784-c32d-456a-ba76-4a38181b3bd2',
                     u'checksum': u'md5:fd2daa13aa14f22d05ab4dbd35697410',
                     u'filetype': u'pdf',
                     u'key': u'10.1093/ptep/ptt095.pdf',
                     u'size': 6319461,
                     u'version_id': u'921bc121-a390-42ec-8907-3faaee041e20'},
                    {u'bucket': u'bc602784-c32d-456a-ba76-4a38181b3bd2',
                     u'checksum': u'md5:d46f22db9ae4827fd90ff1a00fd28f6d',
                     u'filetype': u'pdf/a',
                     u'key': u'10.1093/ptep/ptt095_a.pdf',
                     u'size': 6551161,
                     u'version_id': u'33d47161-cfa1-4076-adb9-1425d8a6ec45'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:899',
                  u'sets': [u'PTEP'],
                  u'updated': u'2018-04-19T14:22:29Z'},
        u'abstracts': [{u'source': u'Oxford University Press/Physical Society of Japan',
                        u'value': u'Dense quantum [...] vortices, axial wallvortex composites, and Skyrmions.'}],
        u'acquisition_source': {u'date': u'2014-01-13T00:00:00',
                                u'method': u'scoap3',
                                u'source': u'Oxford University Press/Physical Society of Japan',
                                u'submission_number': u'c1e1d35643dc11e890c902163e01809a'},
        u'authors': [{u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Department of Physics, Yamagata University, Kojirakawa 1-4-12, '
                                                   u'Yamagata, Yamagata 990-8560, Japan'}],
                      u'full_name': u'Eto, Minoru',
                      u'given_names': u'Minoru',
                      u'raw_name': u'Eto, Minoru',
                      u'surname': u'Eto'},
                     {u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Theoretical Research Division, Nishina Center, RIKEN, Wako '
                                                   u'351-0198, Japan'},
                                        {u'country': u'Japan',
                                         u'value': u'Department of Physics, Sophia University, Tokyo 102-8554, Japan'},
                                        {u'country': u'Japan',
                                         u'value': u'Department of Physics, University of Tokyo, Hongo 7-3-1, '
                                                   u'Bunkyo-ku, Tokyo 113-0033, Japan'}],
                      u'full_name': u'Hirono, Yuji',
                      u'given_names': u'Yuji',
                      u'raw_name': u'Hirono, Yuji',
                      u'surname': u'Hirono'},
                     {u'affiliations': [{u'country': u'Japan',
                                         u'value': u'Department of Physics, and Research and Education Center for '
                                                   u'Natural Sciences, Keio University, Hiyoshi 4-1-1, Yokohama, '
                                                   u'Kanagawa 223-8521, Japan'}],
                      u'full_name': u'Nitta, Muneto',
                      u'given_names': u'Muneto',
                      u'raw_name': u'Nitta, Muneto',
                      u'surname': u'Nitta'},
                     {u'affiliations': [{u'country': u'Japan',
                                         u'value': u'KEK Theory Center, Institute of Particle and Nuclear Studies, '
                                                   u'High Energy Accelerator Research Organization (KEK), 1-1 Oho, '
                                                   u'Tsukuba, Ibaraki 305-0801, Japan'}],
                      u'full_name': u'Yasui, Shigehiro',
                      u'given_names': u'Shigehiro',
                      u'raw_name': u'Yasui, Shigehiro',
                      u'surname': u'Yasui'}],
        u'control_number': u'899',
        u'copyright': [{u'holder': u'',
                        u'material': u'',
                        u'statement': u'The Author(s) 2014',
                        u'year': u'2014'}],
        u'dois': [{u'value': u'10.1093/ptep/ptt095'}],
        u'earliest_date': u'2014-01-01',
        u'files': [],
        u'imprints': [{u'date': u'2014-01-01',
                       u'publisher': u'Oxford University Press/Physical Society of Japan'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'http://creativecommons.org/licenses/by/3.0/'}],
        u'local_files': [{u'value': {u'filetype': u'xml',
                                     u'path': u'http://repo.scoap3.org/record/899/files/main.xml'}},
                         {u'value': {u'filetype': u'pdf',
                                     u'path': u'http://repo.scoap3.org/record/899/files/main.pdf'}},
                         {u'value': {u'filetype': u'pdfa',
                                     u'path': u'http://repo.scoap3.org/record/899/files/main.pdf?subformat=pdfa'}}],
        u'page_nr': [u'149'],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'1',
                               u'journal_title': u'Progress of Theoretical and Experimental Physics',
                               u'journal_volume': u'',
                               u'note': u'',
                               u'page_end': u'',
                               u'page_start': u'012D01',
                               u'pubinfo_freetext': u'',
                               u'year': 2014}],
        u'record_creation_date': u'2014-01-13',
        'arxiv_eprints': {'value': '1308.1535'},
        u'report_numbers': [{u'categories': [u'hep-ph',
                                             u'astro-ph.HE',
                                             u'cond-mat.supr-con',
                                             u'hep-th'],
                             u'primary_category': u'hep-ph',
                             u'source': u'arXiv',
                             u'value': u'arXiv:1308.1535'}],
        u'titles': [{u'source': u'Oxford University Press/Physical Society of Japan',
                     u'subtitle': u'',
                     u'title': u'Vortices and other topological solitons in dense quark matter'}]
    }

    assert run_mapper_with_mock(data) is None


def test_map_old_record_none():
    assert run_mapper_with_mock(None) is None


def test_map_old_record_remove_arxiv_prefix():
    data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_files': [{u'bucket': u'd261c148-07de-4f48-baa3-b2ceecdc543e',
                     u'checksum': u'md5:74d7eedf6327af68fbab93892a9502c6',
                     u'filetype': u'xml',
                     u'key': u'10.1140/epjc/s10052-019-6886-1.xml',
                     u'size': 9608,
                     u'version_id': u'28da1f8f-7825-4182-bc7a-e92218c610b3'},
                    {u'bucket': u'd261c148-07de-4f48-baa3-b2ceecdc543e',
                     u'checksum': u'md5:963c1ded846f7ab780e7eb2cafeb44f6',
                     u'filetype': u'pdf/a',
                     u'key': u'10.1140/epjc/s10052-019-6886-1_a.pdf',
                     u'size': 301257,
                     u'version_id': u'6a485116-1663-4b4c-8c47-cc2095d0fa5d'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:47025',
                  u'sets': [u'EPJC'],
                  u'updated': u'2019-04-28T03:30:20Z'},
        u'abstracts': [{u'source': u'Springer',
                        u'value': u'We investigate spherically symmetric [...] compared to the mass of black hole.'}],
        u'acquisition_source': {u'date': u'2019-04-28T05:30:19.276456',
                                u'method': u'Springer',
                                u'source': u'Springer',
                                u'submission_number': u'eac07980696511e980e602163e01809a'},
        u'arxiv_eprints': [{u'categories': [u'gr-qc', u'hep-th'],
                            u'value': u'arXiv:1801.07973v2'}],
        u'authors': [{u'affiliations': [{u'country': u'China',
                                         u'organization': u'Hebei University',
                                         u'value': u'College of Physical Science and Technology, Hebei University, '
                                                   u'Baoding, 071002, China'},
                                        {u'country': u'China',
                                         u'organization': u'Hebei University',
                                         u'value': u'Hebei Key Lab of Optic-Electronic Information and Materials, '
                                                   u'Hebei University, Baoding, 071002, China'}],
                      u'email': u'yangrongjia@tsinghua.org.cn',
                      u'full_name': u'Yang, Rongjia',
                      u'given_names': u'Rongjia',
                      u'surname': u'Yang'}],
        u'collections': [{u'primary': u'European Physical Journal C'}],
        u'control_number': u'47025',
        u'copyright': [{u'holder': u'The Author(s)',
                        u'material': u'',
                        u'statement': u'',
                        u'year': u'2019'}],
        u'dois': [{u'value': u'10.1140/epjc/s10052-019-6886-1'}],
        u'imprints': [{u'date': u'2019-04-27', u'publisher': u'Springer'}],
        u'license': [{u'license': u'CC-BY-4.0',
                      u'url': u'https://creativecommons.org/licenses//by/4.0'}],
        u'page_nr': [6],
        u'publication_info': [{u'artid': u's10052-019-6886-1',
                               u'journal_issue': u'4',
                               u'journal_title': u'European Physical Journal C',
                               u'journal_volume': u'79',
                               u'material': u'article',
                               u'page_end': u'6',
                               u'page_start': u'1',
                               u'pubinfo_freetext': u'',
                               u'year': 2019}],
        u'record_creation_date': u'2019-04-27T14:30:26.740556',
        u'record_creation_year': 2019,
        u'titles': [{u'source': u'Springer',
                     u'subtitle': u'',
                     u'title': u'Constraints from accretion onto a '
                               u'Tangherlini\u2013Reissner\u2013Nordstrom black hole'}]
    }

    expected_data = data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_files': [{u'bucket': u'd261c148-07de-4f48-baa3-b2ceecdc543e',
                     u'checksum': u'md5:74d7eedf6327af68fbab93892a9502c6',
                     u'filetype': u'xml',
                     u'key': u'10.1140/epjc/s10052-019-6886-1.xml',
                     u'size': 9608,
                     u'version_id': u'28da1f8f-7825-4182-bc7a-e92218c610b3'},
                    {u'bucket': u'd261c148-07de-4f48-baa3-b2ceecdc543e',
                     u'checksum': u'md5:963c1ded846f7ab780e7eb2cafeb44f6',
                     u'filetype': u'pdf/a',
                     u'key': u'10.1140/epjc/s10052-019-6886-1_a.pdf',
                     u'size': 301257,
                     u'version_id': u'6a485116-1663-4b4c-8c47-cc2095d0fa5d'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:47025',
                  u'sets': [u'EPJC'],
                  u'updated': u'2019-04-28T03:30:20Z'},
        u'abstracts': [{u'source': u'Springer',
                        u'value': u'We investigate spherically symmetric [...] compared to the mass of black hole.'}],
        u'acquisition_source': {u'date': u'2019-04-28T05:30:19.276456',
                                u'method': u'Springer',
                                u'source': u'Springer',
                                u'submission_number': u'eac07980696511e980e602163e01809a'},
        u'arxiv_eprints': [{u'categories': [u'gr-qc', u'hep-th'],
                            u'value': u'1801.07973v2'}],
        u'authors': [{u'affiliations': [{u'country': u'China',
                                         u'organization': u'Hebei University',
                                         u'value': u'College of Physical Science and Technology, Hebei University, '
                                                   u'Baoding, 071002, China'},
                                        {u'country': u'China',
                                         u'organization': u'Hebei University',
                                         u'value': u'Hebei Key Lab of Optic-Electronic Information and Materials, '
                                                   u'Hebei University, Baoding, 071002, China'}],
                      u'email': u'yangrongjia@tsinghua.org.cn',
                      u'full_name': u'Yang, Rongjia',
                      u'given_names': u'Rongjia',
                      u'surname': u'Yang'}],
        u'collections': [{u'primary': u'European Physical Journal C'}],
        u'control_number': u'47025',
        u'copyright': [{u'holder': u'The Author(s)',
                        u'material': u'',
                        u'statement': u'',
                        u'year': u'2019'}],
        u'dois': [{u'value': u'10.1140/epjc/s10052-019-6886-1'}],
        u'imprints': [{u'date': u'2019-04-27', u'publisher': u'Springer'}],
        u'license': [{u'license': u'CC-BY-4.0',
                      u'url': u'https://creativecommons.org/licenses//by/4.0'}],
        u'page_nr': [6],
        u'publication_info': [{u'artid': u's10052-019-6886-1',
                               u'journal_issue': u'4',
                               u'journal_title': u'European Physical Journal C',
                               u'journal_volume': u'79',
                               u'material': u'article',
                               u'page_end': u'6',
                               u'page_start': u'1',
                               u'pubinfo_freetext': u'',
                               u'year': 2019}],
        u'record_creation_date': u'2019-04-27T14:30:26.740556',
        u'record_creation_year': 2019,
        u'titles': [{u'source': u'Springer',
                     u'subtitle': u'',
                     u'title': u'Constraints from accretion onto a '
                               u'Tangherlini\u2013Reissner\u2013Nordstrom black hole'}]
    }

    assert run_mapper_with_mock(data).json == expected_data


def test_map_old_record_ahep():
    data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_collections': [u'Advances in High Energy Physics', u'scoap3'],
        u'_files': [{u'bucket': u'8c8e1eba-f2ba-45af-85f5-93ca9137ffe5',
                     u'checksum': u'md5:616258f1ade43b1673c836ae99afb141',
                     u'filetype': u'pdf',
                     u'key': u'10.1155/2018/7308935.pdf',
                     u'size': 2209391,
                     u'version_id': u'af0f4612-9998-4b37-b077-4f11ba420663'},
                    {u'bucket': u'8c8e1eba-f2ba-45af-85f5-93ca9137ffe5',
                     u'checksum': u'md5:73d2bdedcc3414ca9fb79a868f90be98',
                     u'filetype': u'xml',
                     u'key': u'10.1155/2018/7308935.xml',
                     u'size': 257289,
                     u'version_id': u'9ac1b98e-e314-4590-b577-e20e61bc9532'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:40436',
                  u'sets': [u'AHEP'],
                  u'updated': u'2018-05-29T22:00:13Z'},
        u'abstracts': [{u'source': u'Hindawi',
                        u'value': u'The relativistic quantum decay [...] invariant by changing reference frame.'}],
        u'acquisition_source': {u'date': u'2018-05-30T00:00:11.055248',
                                u'method': u'Hindawi',
                                u'source': u'Hindawi',
                                u'submission_number': u'a4c06200638b11e887f202163e01809a'},
        u'additional_files': [{u'access': u'INSPIRE-HIDDEN',
                               u'description': u'HINDAWI',
                               u'type': u'Fulltext',
                               u'url': u'http://downloads.hindawi.com/journals/ahep/2018/7308935.xml'}],
        u'arxiv_eprints': [{u'value': u'arXiv:1803.07709'}],
        u'authors': [{u'affiliations': [{u'country': u'South Africa',
                                         u'value': u'School of Chemistry and Physics, University of KwaZulu-Natal and '
                                                   u'National Institute for Theoretical Physics (NITheP), Westville '
                                                   u'Campus, Durban 4001, South Africa'}],
                      u'full_name': u'Giraldi, Filippo',
                      u'given_names': u'Filippo',
                      u'orcid': u'0000-0002-9060-3475',
                      u'raw_name': u'Giraldi, Filippo',
                      u'surname': u'Giraldi'}],
        u'collections': [{u'primary': u'Advances in High Energy Physics'}],
        u'control_number': u'40436',
        u'copyright': [{u'holder': u'',
                        u'material': u'',
                        u'statement': u'Copyright \xa9 2018 Filippo Giraldi.',
                        u'year': u'2018'}],
        u'dois': [{u'value': u'10.1155/2018/7308935'}],
        u'earliest_date': u'2018-05-29',
        u'file_urls': [u'http://downloads.hindawi.com/journals/ahep/2018/7308935.pdf',
                       u'http://downloads.hindawi.com/journals/ahep/2018/7308935.a.pdf'],
        u'files': [{u'checksum': u'616258f1ade43b1673c836ae99afb141',
                    u'path': u'full/89ea38b517d9083a380bf16263b28fd201ff5c2d.pdf',
                    u'url': u'http://downloads.hindawi.com/journals/ahep/2018/7308935.pdf'},
                   {u'checksum': u'd3db01faa65eed7c71696dff21784b7c',
                    u'path': u'full/a938702dcda15698a1f2d3b1d562c80adba55ec9.pdf',
                    u'url': u'http://downloads.hindawi.com/journals/ahep/2018/7308935.a.pdf'}],
        u'imprints': [{u'date': u'2018-05-29', u'publisher': u'Hindawi'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'http://creativecommons.org/licenses/by/3.0/'}],
        u'page_nr': [u'10'],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'382897',
                               u'journal_title': u'Advances in High Energy Physics',
                               u'journal_volume': u'',
                               u'note': u'',
                               u'page_end': u'',
                               u'page_start': u'7308935',
                               u'pubinfo_freetext': u'',
                               u'year': 2018}],
        u'record_creation_date': u'2018-05-30T00:00:11.055283',
        u'titles': [{u'source': u'Hindawi',
                     u'subtitle': u'',
                     u'title': u'Time Dilation in Relativistic Quantum Decay Laws of Moving Unstable Particles'}]
    }

    expected_data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_files': [{u'bucket': u'8c8e1eba-f2ba-45af-85f5-93ca9137ffe5',
                     u'checksum': u'md5:616258f1ade43b1673c836ae99afb141',
                     u'filetype': u'pdf',
                     u'key': u'10.1155/2018/7308935.pdf',
                     u'size': 2209391,
                     u'version_id': u'af0f4612-9998-4b37-b077-4f11ba420663'},
                    {u'bucket': u'8c8e1eba-f2ba-45af-85f5-93ca9137ffe5',
                     u'checksum': u'md5:73d2bdedcc3414ca9fb79a868f90be98',
                     u'filetype': u'xml',
                     u'key': u'10.1155/2018/7308935.xml',
                     u'size': 257289,
                     u'version_id': u'9ac1b98e-e314-4590-b577-e20e61bc9532'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:40436',
                  u'sets': [u'AHEP'],
                  u'updated': u'2018-05-29T22:00:13Z'},
        u'abstracts': [{u'source': u'Hindawi',
                        u'value': u'The relativistic quantum decay [...] invariant by changing reference frame.'}],
        u'acquisition_source': {u'date': u'2018-05-30T00:00:11.055248',
                                u'method': u'Hindawi',
                                u'source': u'Hindawi',
                                u'submission_number': u'a4c06200638b11e887f202163e01809a'},
        u'arxiv_eprints': [{u'value': u'arXiv:1803.07709', 'categories': ['quant-ph']}],
        u'authors': [{u'affiliations': [{u'country': u'South Africa',
                                         u'value': u'School of Chemistry and Physics, University of KwaZulu-Natal and '
                                                   u'National Institute for Theoretical Physics (NITheP), Westville '
                                                   u'Campus, Durban 4001, South Africa'}],
                      u'full_name': u'Giraldi, Filippo',
                      u'given_names': u'Filippo',
                      u'orcid': u'0000-0002-9060-3475',
                      u'raw_name': u'Giraldi, Filippo',
                      u'surname': u'Giraldi'}],
        u'collections': [{u'primary': u'Advances in High Energy Physics'}],
        u'control_number': u'40436',
        u'copyright': [{u'holder': u'',
                        u'material': u'',
                        u'statement': u'Copyright \xa9 2018 Filippo Giraldi.',
                        u'year': u'2018'}],
        u'dois': [{u'value': u'10.1155/2018/7308935'}],
        u'imprints': [{u'date': u'2018-05-29', u'publisher': u'Hindawi'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'http://creativecommons.org/licenses/by/3.0/'}],
        u'page_nr': [10],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'382897',
                               u'journal_title': u'Advances in High Energy Physics',
                               u'journal_volume': u'',
                               u'note': u'',
                               u'page_end': u'',
                               u'page_start': u'7308935',
                               u'pubinfo_freetext': u'',
                               u'year': 2018}],
        u'record_creation_date': u'2018-05-30T00:00:11.055283',
        u'titles': [{u'source': u'Hindawi',
                     u'subtitle': u'',
                     u'title': u'Time Dilation in Relativistic Quantum Decay Laws of Moving Unstable Particles'}]
    }

    assert run_mapper_with_mock(data).json == expected_data


def test_map_old_record_jhep():
    data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_collections': [u'Journal of High Energy Physics', u'scoap3'],
        u'_files': [{u'bucket': u'f826e653-d834-4991-a52f-458970a0bbd5',
                     u'checksum': u'md5:d4fa2f33ebd2ee8d8073932b79a3bd73',
                     u'filetype': u'xml',
                     u'key': u'10.1007/JHEP10(2018)188.xml',
                     u'size': 9876,
                     u'version_id': u'e9e8328d-176c-496c-b7f6-425153400986'},
                    {u'bucket': u'f826e653-d834-4991-a52f-458970a0bbd5',
                     u'checksum': u'md5:ea8a03e4056377ec61bba650784bb990',
                     u'filetype': u'pdf/a',
                     u'key': u'10.1007/JHEP10(2018)188_a.pdf',
                     u'size': 2113557,
                     u'version_id': u'26041ec6-6c20-4406-90e5-c0f5af28f070'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:43683',
                  u'sets': [u'JHEP'],
                  u'updated': u'2018-11-19T16:52:51Z'},
        u'abstracts': [{u'source': u'Springer',
                        u'value': u'The inert Zee model [...] promising experimental perspectives on that matter.'}],
        u'acquisition_source': {u'date': u'2018-11-19T17:34:33.760479',
                                u'method': u'Springer',
                                u'source': u'Springer',
                                u'submission_number': u'f950c808ec1811e89d1402163e01809a'},
        u'authors': [{u'affiliations': [{u'country': u'Colombia',
                                         u'organization': u'Universidad de Antioquia',
                                         u'value': u'Instituto de F\xedsica, Universidad de Antioquia, Calle 70 No. '
                                                   u'52-21, A.A. 1226, Medell\xedn, Colombia'}],
                      u'email': u'alexandra.gaviria@udea.edu.co',
                      u'full_name': u'Gaviria, Alexandra',
                      u'given_names': u'Alexandra',
                      u'surname': u'Gaviria'},
                     {u'affiliations': [{u'country': u'Colombia',
                                         u'organization': u'Universidad de Antioquia',
                                         u'value': u'Instituto de F\xedsica, Universidad de Antioquia, Calle 70 No. '
                                                   u'52-21, A.A. 1226, Medell\xedn, Colombia'}],
                      u'email': u'robinson.longas@udea.edu.co',
                      u'full_name': u'Longas, Robinson',
                      u'given_names': u'Robinson',
                      u'surname': u'Longas'},
                     {u'affiliations': [{u'country': u'Colombia',
                                         u'organization': u'Universidad de Antioquia',
                                         u'value': u'Instituto de F\xedsica, Universidad de Antioquia, Calle 70 No. '
                                                   u'52-21, A.A. 1226, Medell\xedn, Colombia'}],
                      u'email': u'oalberto.zapata@udea.edu.co',
                      u'full_name': u'Zapata, \xd3scar',
                      u'given_names': u'\xd3scar',
                      u'surname': u'Zapata'}],
        u'collections': [{u'primary': u'Journal of High Energy Physics'}],
        u'control_number': u'43683',
        u'copyright': [{u'holder': u'The Author(s)',
                        u'material': u'Article',
                        u'statement': u'',
                        u'year': u'2018'}],
        u'dois': [{u'value': u'10.1007/JHEP10(2018)188'}],
        u'earliest_date': u'2018-10-30',
        u'files': [],
        u'imprints': [{u'date': u'2018-10-30', u'publisher': u'Springer'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'https://creativecommons.org/licenses/by/3.0'}],
        u'local_files': [{u'value': {u'filetype': u'xml',
                                     u'path': u'/eos/project/s/scoap3repo/BETA/harvesting/Springer/unpacked/ftp_PUB_18-'
                                              u'10-31_12-02-08_ckLIKo/JOU=13130/VOL=2018.2018/ISU=10/ART=9288/13130_201'
                                              u'8_Article_9288.xml.scoap'}},
                         {u'value': {u'filetype': u'pdf/a',
                                     u'path': u'/eos/project/s/scoap3repo/BETA/harvesting/Springer/unpacked/ftp_PUB_18-'
                                              u'10-31_12-02-08_ckLIKo/JOU=13130/VOL=2018.2018/ISU=10/ART=9288/BodyRef/P'
                                              u'DF/13130_2018_Article_9288.pdf'}}],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'10',
                               u'journal_title': u'Journal of High Energy Physics',
                               u'journal_volume': u'2018',
                               u'note': u'',
                               u'page_end': u'19',
                               u'page_start': u'1',
                               u'pubinfo_freetext': u'',
                               u'year': 2018}],
        u'record_creation_date': u'2018-11-19T17:34:33.760497',
        u'titles': [{u'source': u'Springer',
                     u'subtitle': u'',
                     u'title': u'Charged lepton flavor violation and electric dipole moments in the inert Zee model'}]
    }

    expected_data = {
        u'$schema': u'http://beta.scoap3.org/schemas/hep.json',
        u'_files': [{u'bucket': u'f826e653-d834-4991-a52f-458970a0bbd5',
                     u'checksum': u'md5:d4fa2f33ebd2ee8d8073932b79a3bd73',
                     u'filetype': u'xml',
                     u'key': u'10.1007/JHEP10(2018)188.xml',
                     u'size': 9876,
                     u'version_id': u'e9e8328d-176c-496c-b7f6-425153400986'},
                    {u'bucket': u'f826e653-d834-4991-a52f-458970a0bbd5',
                     u'checksum': u'md5:ea8a03e4056377ec61bba650784bb990',
                     u'filetype': u'pdf/a',
                     u'key': u'10.1007/JHEP10(2018)188_a.pdf',
                     u'size': 2113557,
                     u'version_id': u'26041ec6-6c20-4406-90e5-c0f5af28f070'}],
        u'_oai': {u'id': u'oai:beta.scoap3.org:43683',
                  u'sets': [u'JHEP'],
                  u'updated': u'2018-11-19T16:52:51Z'},
        u'abstracts': [{u'source': u'Springer',
                        u'value': u'The inert Zee model [...] promising experimental perspectives on that matter.'}],
        u'acquisition_source': {u'date': u'2018-11-19T17:34:33.760479',
                                u'method': u'Springer',
                                u'source': u'Springer',
                                u'submission_number': u'f950c808ec1811e89d1402163e01809a'},
        u'authors': [{u'affiliations': [{u'country': u'Colombia',
                                         u'organization': u'Universidad de Antioquia',
                                         u'value': u'Instituto de F\xedsica, Universidad de Antioquia, Calle 70 No. '
                                                   u'52-21, A.A. 1226, Medell\xedn, Colombia'}],
                      u'email': u'alexandra.gaviria@udea.edu.co',
                      u'full_name': u'Gaviria, Alexandra',
                      u'given_names': u'Alexandra',
                      u'surname': u'Gaviria'},
                     {u'affiliations': [{u'country': u'Colombia',
                                         u'organization': u'Universidad de Antioquia',
                                         u'value': u'Instituto de F\xedsica, Universidad de Antioquia, Calle 70 No. '
                                                   u'52-21, A.A. 1226, Medell\xedn, Colombia'}],
                      u'email': u'robinson.longas@udea.edu.co',
                      u'full_name': u'Longas, Robinson',
                      u'given_names': u'Robinson',
                      u'surname': u'Longas'},
                     {u'affiliations': [{u'country': u'Colombia',
                                         u'organization': u'Universidad de Antioquia',
                                         u'value': u'Instituto de F\xedsica, Universidad de Antioquia, Calle 70 No. '
                                                   u'52-21, A.A. 1226, Medell\xedn, Colombia'}],
                      u'email': u'oalberto.zapata@udea.edu.co',
                      u'full_name': u'Zapata, \xd3scar',
                      u'given_names': u'\xd3scar',
                      u'surname': u'Zapata'}],
        u'collections': [{u'primary': u'Journal of High Energy Physics'}],
        u'control_number': u'43683',
        u'copyright': [{u'holder': u'The Author(s)',
                        u'material': u'Article',
                        u'statement': u'',
                        u'year': u'2018'}],
        u'dois': [{u'value': u'10.1007/JHEP10(2018)188'}],
        u'imprints': [{u'date': u'2018-10-30', u'publisher': u'Springer'}],
        u'license': [{u'license': u'CC-BY-3.0',
                      u'url': u'https://creativecommons.org/licenses/by/3.0'}],
        u'publication_info': [{u'artid': u'',
                               u'journal_issue': u'10',
                               u'journal_title': u'Journal of High Energy Physics',
                               u'journal_volume': u'2018',
                               u'note': u'',
                               u'page_end': u'19',
                               u'page_start': u'1',
                               u'pubinfo_freetext': u'',
                               u'year': 2018}],
        u'record_creation_date': u'2018-11-19T17:34:33.760497',
        u'titles': [{u'source': u'Springer',
                     u'subtitle': u'',
                     u'title': u'Charged lepton flavor violation and electric dipole moments in the inert Zee model'}]
    }

    assert run_mapper_with_mock(data).json == expected_data
